#!/usr/bin/env node

require('dotenv').config();

const fs = require('fs');
const nock = require('nock');
const createProbot = require('probot');
const stripAnsi = require('strip-ansi');

const plugin = require('../');

/* eslint-disable camelcase */
nock.recorder.rec({
  enable_reqheaders_recording: true,
  logging(content) {
    const entry =
`
<!-- Start Entry -->

${JSON.stringify(content, null, 2)}

<!-- End Entry -->
`;
    fs.appendFileSync('.nock-log', entry);
  },
  output_objects: true,
  use_separator: false
});
/* eslint-enable camelcase */

function throwError(message) {
  throw new Error(message);
}

process.env.LOG_LEVEL = 'trace';

const stdoutWrite = process.stdout.write;
const fileStream = fs.createWriteStream('.probot-log');
process.stdout.write = (chunk, encoding, callback) => {
  stdoutWrite.call(process.stdout, chunk, encoding, callback);
  fileStream.write(stripAnsi(chunk), encoding);
};

const probot = createProbot({
  id: process.env.APP_ID || throwError('App ID not specified.'),
  secret: process.env.WEBHOOK_SECRET || 'development',
  cert: process.env.PRIVATE_KEY || throwError('Private Key not specified.'),
  port: 3000
});

probot.load(plugin);
probot.start();
