#!/usr/bin/env node

require('dotenv').config();

const fs = require('fs');
const nock = require('nock');
const createProbot = require('probot');

const plugin = require('../');

nock.recorder.rec({
  enable_reqheaders_recording: true, // eslint-disable-line camelcase
  logging(content) {
    fs.appendFileSync('.nock-log', content);
  }
});

function throwError(message) {
  throw new Error(message);
}

const probot = createProbot({
  id: process.env.INTEGRATION_ID || throwError('Integration ID not specified.'),
  secret: process.env.WEBHOOK_SECRET || 'development',
  cert: process.env.PRIVATE_KEY || throwError('Private Key not specified.'),
  port: 3000
});

probot.load(plugin);
probot.start();
